<?php

#define("API_TOKEN", getenv('API_TOKEN'));
define("API_SECRET", getenv('API_SECRET'));

// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

$client = new \PrivatePackagist\ApiClient\Client();
$client->authenticate(getenv('API_TOKEN'), 'API_SECRET');

$fileName='hale-compiled.zip';
$file=file_get_contents($fileName);
$response=$client->packages()->artifacts()->create($file, 'application/zip', $fileName);
$artifactId=$response['id'];
$client->packages()->createArtifactPackage([$artifactId]);
